"""Initial Migration

Revision ID: 243491f837f4
Revises: 
Create Date: 2024-05-22 23:22:48.541385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243491f837f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Autores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Localizacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Obras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('localizacao_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['Autores.id'], ),
    sa.ForeignKeyConstraint(['localizacao_id'], ['Localizacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Esculturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('peso', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['Obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pinturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('tecnica', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['Obras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pinturas')
    op.drop_table('Esculturas')
    op.drop_table('Obras')
    op.drop_table('Localizacoes')
    op.drop_table('Autores')
    # ### end Alembic commands ###
