"""Adicao de todas as controllers

Revision ID: 589384e9241d
Revises: fecfa0b02b1d
Create Date: 2024-05-24 09:22:24.500077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589384e9241d'
down_revision = 'fecfa0b02b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Guias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Visitantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Segurancas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('localizacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['localizacao_id'], ['Localizacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Visitas_Guiadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grupo', sa.String(length=255), nullable=True),
    sa.Column('data_visita', sa.Date(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('guia_responsavel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guia_responsavel_id'], ['Guias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ingressos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitante_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('data_visita', sa.Date(), nullable=True),
    sa.Column('visita_guiada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['visita_guiada_id'], ['Visitas_Guiadas.id'], ),
    sa.ForeignKeyConstraint(['visitante_id'], ['Visitantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Obras_Exposicoes',
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('exposicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exposicao_id'], ['Exposicoes.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['Obras.id'], ),
    sa.PrimaryKeyConstraint('obra_id', 'exposicao_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Obras_Exposicoes')
    op.drop_table('Ingressos')
    op.drop_table('Visitas_Guiadas')
    op.drop_table('Segurancas')
    op.drop_table('Visitantes')
    op.drop_table('Guias')
    # ### end Alembic commands ###
