"""Adicao de ObrasExposicao

Revision ID: 77875a354f23
Revises: 82d6e547f808
Create Date: 2024-05-26 22:28:31.214713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '77875a354f23'
down_revision = '82d6e547f808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Obras_Exposicoes',
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('exposicao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exposicao_id'], ['Exposicoes.id'], ),
    sa.ForeignKeyConstraint(['obra_id'], ['Obras.id'], ),
    sa.PrimaryKeyConstraint('obra_id', 'exposicao_id')
    )
    op.drop_table('sysdiagrams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61F094E94D')
    )
    op.drop_table('Obras_Exposicoes')
    # ### end Alembic commands ###
