"""Adicao de instituicao e mudanda de Emprestimo

Revision ID: 82d6e547f808
Revises: 589384e9241d
Create Date: 2024-05-26 20:43:35.542395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d6e547f808'
down_revision = '589384e9241d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Instituicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Obras_Exposicoes')
    with op.batch_alter_table('Emprestimos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Instituicoes', ['instituicao_id'], ['id'])
        batch_op.drop_column('instituicao_solicitante')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Emprestimos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instituicao_solicitante', sa.VARCHAR(length=255, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instituicao_id')

    op.create_table('Obras_Exposicoes',
    sa.Column('obra_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exposicao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exposicao_id'], ['Exposicoes.id'], name='FK__Obras_Exp__expos__619B8048'),
    sa.ForeignKeyConstraint(['obra_id'], ['Obras.id'], name='FK__Obras_Exp__obra___628FA481'),
    sa.PrimaryKeyConstraint('obra_id', 'exposicao_id', name='PK__Obras_Ex__1E94EBD1EE395F32')
    )
    op.drop_table('Instituicoes')
    # ### end Alembic commands ###
