"""Adição de delete cascate no relacionamento ManyToMany exhibition_work_of_art

Revision ID: d4c85eb54527
Revises: 21a3d6a52dba
Create Date: 2024-06-22 08:54:30.961818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c85eb54527'
down_revision = '21a3d6a52dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_of_art_exhibitions', schema=None) as batch_op:
        batch_op.drop_constraint('FK__works_of___work___5CD6CB2B', type_='foreignkey')
        batch_op.drop_constraint('FK__works_of___exhib__5BE2A6F2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'works_of_art', ['work_of_art_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exhibitions', ['exhibition_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works_of_art_exhibitions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__works_of___exhib__5BE2A6F2', 'exhibitions', ['exhibition_id'], ['id'])
        batch_op.create_foreign_key('FK__works_of___work___5CD6CB2B', 'works_of_art', ['work_of_art_id'], ['id'])

    # ### end Alembic commands ###
