"""Adicao de todas as views

Revision ID: fecfa0b02b1d
Revises: 243491f837f4
Create Date: 2024-05-23 20:38:04.437105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecfa0b02b1d'
down_revision = '243491f837f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exposicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Emprestimos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=True),
    sa.Column('data_emprestimo', sa.Date(), nullable=True),
    sa.Column('data_retorno', sa.Date(), nullable=True),
    sa.Column('instituicao_solicitante', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['Obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Emprestimos')
    op.drop_table('Exposicoes')
    # ### end Alembic commands ###
